language: perl
perl:
- 5.18
- 5.16
- 5.14
- 5.12
- 5.10
- 5.8
sudo: false

install:
- git clone --depth=1 --branch=master
  git://github.com/ingydotnet/test-base-pm ../testml-pm
- cpanm --quiet --notest
  File::Find::Rule
  Template
  Spiffy
  Devel::Cover::Report::Coveralls

script:
- PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine
  PERL5LIB=../testml-pm/lib
  prove -lv t/
- cover

after_success:
- cover -report coveralls
